apiVersion: v1
kind: Pod
metadata:
  name: mikepod
  namespace: miketest
  labels:
    name: mikeapp
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi