apiVersion: v1
kind: Pod
metadata:
  name: mikepod1
  namespace: miketest
  labels:
    name: mikeapp
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
      lifecycle:
        preStop:
          exec:
            command: ["sleep", "50"]
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
  terminationGracePeriodSeconds: 60